import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import 'app_exception.dart';

class TranscriptService {
  TranscriptService._();
  static final TranscriptService instance = TranscriptService._();

  final YoutubeExplode _yt = YoutubeExplode();

  void _log(String msg) {
    if (kDebugMode) debugPrint('[TranscriptService] $msg');
  }

  // ──────────────────────────────────────────────────────────
  // Public API
  // ──────────────────────────────────────────────────────────

  /// Fetches the transcript for [videoId].
  ///
  /// Returns `(text, languageCode)`.
  ///
  /// Uses youtube_explode_dart to discover caption tracks, then fetches
  /// the raw XML ourselves to avoid its strict XML parser issues.
  Future<({String text, String languageCode})> getTranscript(String videoId) async {
    _log('Fetching transcript for $videoId');

    late ClosedCaptionManifest manifest;
    try {
      manifest = await _yt.videos.closedCaptions
          .getManifest(VideoId(videoId))
          .timeout(const Duration(seconds: 15));
    } on SocketException {
      throw const AppException(
        'No internet connection.',
        code: 'no_internet',
      );
    } on VideoUnplayableException {
      throw const AppException(
        'This video is unavailable or private.',
        code: 'video_unavailable',
      );
    } catch (e) {
      _log('Failed to get caption manifest: $e');
      throw const AppException(
        'This video has no captions. Try a different video.',
        code: 'no_captions',
      );
    }

    final track = _selectBestTrack(manifest);
    if (track == null) {
      throw const AppException(
        'This video has no captions. Try a different video.',
        code: 'no_captions',
      );
    }

    _log('Using caption track: ${track.language.code} (auto: ${track.isAutoGenerated})');

    // Fetch the raw caption XML ourselves instead of using youtube_explode's
    // built-in parser, which chokes on some YouTube XML responses.
    try {
      final baseUrl = track.url.toString();

      // Try json3 format first (more reliable), then srv1 (XML).
      String? text;
      for (final fmt in ['json3', 'srv1']) {
        final url = baseUrl.replaceFirst(RegExp(r'fmt=[^&]*'), 'fmt=$fmt');
        _log('Fetching captions (fmt=$fmt) from: $url');
        final body = await _fetchCaptionBody(url);
        _log('Caption response (fmt=$fmt): ${body.length} chars');

        if (body.isEmpty) continue;

        if (fmt == 'json3') {
          text = _parseTranscriptFromJson3(body);
        } else {
          text = _parseTranscriptFromXml(body);
        }

        if (text != null && text.isNotEmpty) break;
      }

      if (text == null || text.isEmpty) {
        throw const AppException(
          'This video has no captions. Try a different video.',
          code: 'no_captions',
        );
      }

      _log('Transcript fetched: ${text.length} chars, lang: ${track.language.code}');
      return (text: text, languageCode: track.language.code);
    } on AppException {
      rethrow;
    } on SocketException {
      throw const AppException(
        'No internet connection.',
        code: 'no_internet',
      );
    } catch (e) {
      _log('Failed to fetch captions: $e (${e.runtimeType})');
      throw const AppException(
        'This video has no captions. Try a different video.',
        code: 'no_captions',
      );
    }
  }

  /// Extracts basic metadata for [videoId].
  ///
  /// Returns a map with keys: `title`, `author`, `lengthSeconds`.
  Future<Map<String, String>> getVideoMetadata(String videoId) async {
    _log('Fetching metadata for $videoId');

    try {
      final video = await _yt.videos
          .get(VideoId(videoId))
          .timeout(const Duration(seconds: 15));

      return {
        'title': video.title,
        'author': video.author,
        'lengthSeconds': (video.duration?.inSeconds ?? 0).toString(),
      };
    } on SocketException {
      throw const AppException(
        'No internet connection.',
        code: 'no_internet',
      );
    } on VideoUnplayableException {
      throw const AppException(
        'This video is unavailable or private.',
        code: 'video_unavailable',
      );
    } catch (e) {
      _log('Failed to get metadata: $e');
      throw const AppException(
        'This video is unavailable or private.',
        code: 'video_unavailable',
      );
    }
  }

  // ──────────────────────────────────────────────────────────
  // Audio download (fallback when no captions)
  // ──────────────────────────────────────────────────────────

  /// Downloads the audio stream for [videoId] as bytes.
  ///
  /// Returns `(audioBytes, mimeType)`. Picks the lowest-bitrate audio-only
  /// stream to minimize download size and Gemini token usage.
  Future<({Uint8List bytes, String mimeType})> getAudioBytes(String videoId) async {
    _log('Downloading audio for $videoId');

    late StreamManifest manifest;
    try {
      manifest = await _yt.videos.streamsClient
          .getManifest(VideoId(videoId))
          .timeout(const Duration(seconds: 20));
    } on SocketException {
      throw const AppException('No internet connection.', code: 'no_internet');
    } on VideoUnplayableException {
      throw const AppException(
        'This video is unavailable or private.',
        code: 'video_unavailable',
      );
    } catch (e) {
      _log('Failed to get stream manifest: $e');
      throw const AppException(
        'Could not download video audio. Try a different video.',
        code: 'audio_unavailable',
      );
    }

    // Pick the smallest audio-only stream.
    final audioStreams = manifest.audioOnly.toList()
      ..sort((a, b) => a.size.totalBytes.compareTo(b.size.totalBytes));

    if (audioStreams.isEmpty) {
      throw const AppException(
        'Could not download video audio. Try a different video.',
        code: 'audio_unavailable',
      );
    }

    final stream = audioStreams.first;
    _log('Audio stream: ${stream.codec.subtype}, ${stream.size.totalMegaBytes.toStringAsFixed(1)} MB');

    // Cap at 20 MB to avoid OOM and Gemini limits.
    if (stream.size.totalMegaBytes > 20) {
      throw const AppException(
        'This video is too long to process without captions. Try a shorter video.',
        code: 'audio_too_large',
      );
    }

    try {
      final dataStream = _yt.videos.streamsClient.get(stream);
      final chunks = <List<int>>[];
      await for (final chunk in dataStream) {
        chunks.add(chunk);
      }
      final bytes = Uint8List.fromList(chunks.expand((c) => c).toList());
      _log('Audio downloaded: ${bytes.length} bytes');

      // Map codec to MIME type for Gemini.
      final mimeType = switch (stream.codec.subtype.toLowerCase()) {
        'mp4a' || 'aac' || 'mp4' => 'audio/mp4',
        'opus' => 'audio/webm',
        'vorbis' => 'audio/ogg',
        _ => 'audio/mp4',
      };

      return (bytes: bytes, mimeType: mimeType);
    } on SocketException {
      throw const AppException('No internet connection.', code: 'no_internet');
    } catch (e) {
      _log('Audio download failed: $e');
      throw const AppException(
        'Could not download video audio. Try a different video.',
        code: 'audio_download_failed',
      );
    }
  }

  // ──────────────────────────────────────────────────────────
  // Innertube ANDROID API (bypasses youtube_explode_dart)
  // ──────────────────────────────────────────────────────────

  static const _innertubeUrl =
      'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
  static const _androidUserAgent =
      'com.google.android.youtube/20.10.38 (Linux; U; Android 14)';

  /// Fetches transcript + metadata via YouTube Innertube ANDROID API.
  ///
  /// This works from mobile devices (residential IPs) where the ANDROID client
  /// returns caption track URLs that don't require JS signature decryption.
  /// Returns null if no captions are available.
  Future<({String transcript, String lang, String title, String author})?> getTranscriptViaInnertube(
      String videoId) async {
    _log('Innertube: fetching player response for $videoId');

    final playerRes = await http.post(
      Uri.parse(_innertubeUrl),
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': _androidUserAgent,
      },
      body: jsonEncode({
        'videoId': videoId,
        'context': {
          'client': {
            'clientName': 'ANDROID',
            'clientVersion': '20.10.38',
          },
        },
      }),
    ).timeout(const Duration(seconds: 15));

    if (playerRes.statusCode != 200) {
      _log('Innertube: player API returned ${playerRes.statusCode}');
      return null;
    }

    final data = jsonDecode(playerRes.body) as Map<String, dynamic>;

    // Check playability
    final status = (data['playabilityStatus'] as Map<String, dynamic>?)?['status'];
    if (status == 'ERROR' || status == 'UNPLAYABLE') {
      _log('Innertube: video is $status');
      return null;
    }

    // Extract metadata
    final videoDetails = data['videoDetails'] as Map<String, dynamic>? ?? {};
    String title = (videoDetails['title'] as String?) ?? '';
    String author = (videoDetails['author'] as String?) ?? '';

    // Fallback to oEmbed for metadata
    if (title.isEmpty) {
      try {
        final oEmbed = await http.get(
          Uri.parse('https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=$videoId&format=json'),
        ).timeout(const Duration(seconds: 10));
        if (oEmbed.statusCode == 200) {
          final oData = jsonDecode(oEmbed.body) as Map<String, dynamic>;
          title = (oData['title'] as String?) ?? '';
          author = (oData['author_name'] as String?) ?? '';
        }
      } catch (_) {}
    }

    // Extract caption tracks
    final captions = data['captions'] as Map<String, dynamic>? ?? {};
    final renderer = captions['playerCaptionsTracklistRenderer'] as Map<String, dynamic>? ?? {};
    final tracks = (renderer['captionTracks'] as List<dynamic>?) ?? [];

    if (tracks.isEmpty) {
      _log('Innertube: no caption tracks found');
      return null;
    }

    _log('Innertube: found ${tracks.length} caption tracks');

    // Select best track (same priority as edge function)
    Map<String, dynamic>? bestTrack;
    int bestScore = -1;

    for (final t in tracks) {
      final track = t as Map<String, dynamic>;
      final lang = ((track['languageCode'] as String?) ?? '').toLowerCase();
      final isEnglish = lang.startsWith('en');
      final isAuto = track['kind'] == 'asr';

      int score;
      if (isEnglish && !isAuto) {
        score = 4;
      } else if (isEnglish && isAuto) {
        score = 3;
      } else if (!isEnglish && !isAuto) {
        score = 2;
      } else {
        score = 1;
      }

      if (score > bestScore) {
        bestScore = score;
        bestTrack = track;
      }
    }

    if (bestTrack == null) return null;

    final baseUrl = bestTrack['baseUrl'] as String;
    final lang = (bestTrack['languageCode'] as String?) ?? 'en';
    _log('Innertube: best track lang=$lang, fetching transcript');

    // Fetch transcript with json3 format
    final captionUrl = baseUrl.contains('&fmt=')
        ? baseUrl.replaceFirst(RegExp(r'&fmt=[^&]*'), '&fmt=json3')
        : '$baseUrl&fmt=json3';

    final captionRes = await http.get(
      Uri.parse(captionUrl),
      headers: {'User-Agent': _androidUserAgent},
    ).timeout(const Duration(seconds: 15));

    if (captionRes.statusCode != 200 || captionRes.body.isEmpty) {
      _log('Innertube: caption fetch returned ${captionRes.statusCode}, ${captionRes.body.length} bytes');
      return null;
    }

    final body = captionRes.body;
    String? transcript;

    if (body.trimLeft().startsWith('{')) {
      // JSON format
      transcript = _parseTranscriptFromJson3(body);
    } else if (body.trimLeft().startsWith('<')) {
      // XML format (timedtext format 3 with <s> tags or srv1 with <text> tags)
      transcript = _parseTranscriptFromXmlTimedtext(body);
      transcript ??= _parseTranscriptFromXml(body);
    }

    if (transcript == null || transcript.isEmpty) {
      _log('Innertube: transcript parsing returned empty');
      return null;
    }

    // Cap transcript length
    final isNonLatin = RegExp(r'[^\u0000-\u024F]').hasMatch(
        transcript.length > 100 ? transcript.substring(0, 100) : transcript);
    final maxChars = isNonLatin ? 12000 : 8000;
    if (transcript.length > maxChars) {
      transcript = transcript.substring(0, maxChars);
    }

    _log('Innertube: transcript ready — ${transcript.length} chars, lang=$lang');
    return (transcript: transcript, lang: lang, title: title, author: author);
  }

  /// Parse XML timedtext format 3 (<s> tags inside <p> tags).
  String? _parseTranscriptFromXmlTimedtext(String xml) {
    final sTagPattern = RegExp(r'<s[^>]*>([^<]*)</s>');
    final matches = sTagPattern.allMatches(xml);
    if (matches.isEmpty) return null;

    final parts = matches
        .map((m) => (m.group(1) ?? '').trim())
        .where((s) => s.isNotEmpty)
        .toList();

    return parts.isEmpty ? null : parts.join(' ');
  }

  // ──────────────────────────────────────────────────────────
  // Caption fetching & parsing
  // ──────────────────────────────────────────────────────────

  Future<String> _fetchCaptionBody(String captionUrl) async {
    late http.Response response;
    try {
      response = await http
          .get(Uri.parse(captionUrl))
          .timeout(const Duration(seconds: 15));
      _log('Caption fetch HTTP status: ${response.statusCode}, body length: ${response.body.length}');
    } on SocketException {
      _log('Caption fetch: SocketException');
      throw const AppException('No internet connection.', code: 'no_internet');
    } catch (e) {
      _log('Caption fetch failed: $e');
      throw const AppException('No internet connection.', code: 'no_internet');
    }

    if (response.statusCode != 200) {
      _log('Caption fetch: non-200 status ${response.statusCode}');
      return '';
    }

    return response.body;
  }

  /// Parses YouTube json3 caption format.
  String? _parseTranscriptFromJson3(String body) {
    try {
      final json = jsonDecode(body) as Map<String, dynamic>;
      final events = json['events'] as List<dynamic>? ?? [];
      final buffer = StringBuffer();

      for (final event in events) {
        final segs = event['segs'] as List<dynamic>?;
        if (segs == null) continue;
        for (final seg in segs) {
          final text = (seg['utf8'] as String?) ?? '';
          if (text == '\n') {
            buffer.write(' ');
          } else {
            buffer.write(text);
          }
        }
      }

      return buffer.toString().trim();
    } catch (e) {
      _log('json3 parse failed: $e');
      return null;
    }
  }

  /// Extracts text from all `<text>` elements in caption XML using regex.
  String? _parseTranscriptFromXml(String xml) {
    final textTagPattern = RegExp(r'<text[^>]*>([\s\S]*?)</text>');
    final matches = textTagPattern.allMatches(xml);

    if (matches.isEmpty) return null;

    final parts = matches
        .map((m) => _decodeHtmlEntities(m.group(1) ?? '').trim())
        .where((s) => s.isNotEmpty)
        .toList();

    final result = parts.join(' ');
    return result.isEmpty ? null : result;
  }

  String _decodeHtmlEntities(String input) {
    return input
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&quot;', '"')
        .replaceAll('&#39;', "'")
        .replaceAll('&apos;', "'")
        .replaceAll('\n', ' ')
        .replaceAll(RegExp(r'<[^>]+>'), '');
  }

  // ──────────────────────────────────────────────────────────
  // Track selection
  // ──────────────────────────────────────────────────────────

  /// Selects the best caption track from the manifest.
  ///
  /// Priority:
  ///   1. Manual English track
  ///   2. Auto-generated English track
  ///   3. Any manual track
  ///   4. Any auto-generated track
  ClosedCaptionTrackInfo? _selectBestTrack(ClosedCaptionManifest manifest) {
    final tracks = manifest.tracks;
    if (tracks.isEmpty) return null;

    ClosedCaptionTrackInfo? best;
    int bestScore = -1;

    for (final track in tracks) {
      final lang = track.language.code.toLowerCase();
      final isEnglish = lang.startsWith('en');
      final isManual = !track.isAutoGenerated;

      final int score;
      if (isEnglish && isManual) {
        score = 4;
      } else if (isEnglish && !isManual) {
        score = 3;
      } else if (!isEnglish && isManual) {
        score = 2;
      } else {
        score = 1;
      }

      if (score > bestScore) {
        bestScore = score;
        best = track;
      }
    }

    return best;
  }
}
