export interface RecipeEntry {
  name: string;
  category: string;
  region: string;
}

export const RECIPES: RecipeEntry[] = [
  // ── Dal & Curry (100) ────────────────────────────────────────
  { name: "Butter Chicken", category: "Dal & Curry", region: "North Indian" },
  { name: "Dal Makhani", category: "Dal & Curry", region: "North Indian" },
  { name: "Palak Paneer", category: "Dal & Curry", region: "North Indian" },
  { name: "Paneer Butter Masala", category: "Dal & Curry", region: "North Indian" },
  { name: "Chana Masala", category: "Dal & Curry", region: "North Indian" },
  { name: "Rajma", category: "Dal & Curry", region: "North Indian" },
  { name: "Kadai Paneer", category: "Dal & Curry", region: "North Indian" },
  { name: "Shahi Paneer", category: "Dal & Curry", region: "North Indian" },
  { name: "Matar Paneer", category: "Dal & Curry", region: "North Indian" },
  { name: "Aloo Gobi", category: "Dal & Curry", region: "North Indian" },
  { name: "Dal Tadka", category: "Dal & Curry", region: "North Indian" },
  { name: "Dal Fry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Chicken Curry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Mutton Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Keema Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Egg Curry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Fish Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Prawn Masala", category: "Dal & Curry", region: "South Indian" },
  { name: "Chicken Tikka Masala", category: "Dal & Curry", region: "North Indian" },
  { name: "Baingan Bharta", category: "Dal & Curry", region: "North Indian" },
  { name: "Aloo Matar", category: "Dal & Curry", region: "North Indian" },
  { name: "Bhindi Masala", category: "Dal & Curry", region: "North Indian" },
  { name: "Mix Vegetable Curry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Kadhi Pakora", category: "Dal & Curry", region: "North Indian" },
  { name: "Sarson Ka Saag", category: "Dal & Curry", region: "North Indian" },
  { name: "Lauki Ki Sabzi", category: "Dal & Curry", region: "North Indian" },
  { name: "Tindora Sabzi", category: "Dal & Curry", region: "North Indian" },
  { name: "Soya Chunks Curry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Arhar Dal", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Moong Dal", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Masoor Dal", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Urad Dal", category: "Dal & Curry", region: "North Indian" },
  { name: "Sambhar", category: "Dal & Curry", region: "South Indian" },
  { name: "Rasam", category: "Dal & Curry", region: "South Indian" },
  { name: "Chicken Chettinad", category: "Dal & Curry", region: "South Indian" },
  { name: "Kerala Fish Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Prawn Coconut Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Kofta Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Navratan Korma", category: "Dal & Curry", region: "North Indian" },
  { name: "Paneer Lababdar", category: "Dal & Curry", region: "North Indian" },
  { name: "Chicken Korma", category: "Dal & Curry", region: "North Indian" },
  { name: "Saag Chicken", category: "Dal & Curry", region: "North Indian" },
  { name: "Jackfruit Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Drumstick Sambar", category: "Dal & Curry", region: "South Indian" },
  { name: "Black Eyed Peas Curry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Green Moong Dal", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Aloo Palak", category: "Dal & Curry", region: "North Indian" },
  { name: "Methi Malai Paneer", category: "Dal & Curry", region: "North Indian" },
  { name: "Dhingri Matar", category: "Dal & Curry", region: "North Indian" },
  { name: "Lamb Rogan Josh", category: "Dal & Curry", region: "North Indian" },
  { name: "Chicken Do Pyaza", category: "Dal & Curry", region: "North Indian" },
  { name: "Paneer Bhurji", category: "Dal & Curry", region: "North Indian" },
  { name: "Chicken Bhuna", category: "Dal & Curry", region: "North Indian" },
  { name: "Sindhi Kadhi", category: "Dal & Curry", region: "West Indian" },
  { name: "Goan Fish Curry", category: "Dal & Curry", region: "West Indian" },
  { name: "Kolhapuri Chicken", category: "Dal & Curry", region: "West Indian" },
  { name: "Ennai Kathirikai", category: "Dal & Curry", region: "South Indian" },
  { name: "Moru Kootan", category: "Dal & Curry", region: "South Indian" },
  { name: "Podi Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Mustard Fish Curry", category: "Dal & Curry", region: "East Indian" },
  { name: "Kosha Mangsho", category: "Dal & Curry", region: "East Indian" },
  { name: "Chingri Malai Curry", category: "Dal & Curry", region: "East Indian" },
  { name: "Aloo Posto", category: "Dal & Curry", region: "East Indian" },
  { name: "Dhokar Dalna", category: "Dal & Curry", region: "East Indian" },
  { name: "Nihari", category: "Dal & Curry", region: "North Indian" },
  { name: "Paya Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Haleem", category: "Dal & Curry", region: "North Indian" },
  { name: "Dal Baati Churma", category: "Dal & Curry", region: "West Indian" },
  { name: "Pithla", category: "Dal & Curry", region: "West Indian" },
  { name: "Amti", category: "Dal & Curry", region: "West Indian" },
  { name: "Zunka", category: "Dal & Curry", region: "West Indian" },
  { name: "Sabudana Khichdi", category: "Dal & Curry", region: "West Indian" },
  { name: "Bharwa Baingan", category: "Dal & Curry", region: "North Indian" },
  { name: "Stuffed Capsicum", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Turai Ki Sabzi", category: "Dal & Curry", region: "North Indian" },
  { name: "Kathal Sabzi", category: "Dal & Curry", region: "North Indian" },
  { name: "Suran Ki Sabzi", category: "Dal & Curry", region: "North Indian" },
  { name: "Kala Chana Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Lobiya Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Chicken Keema Matar", category: "Dal & Curry", region: "North Indian" },
  { name: "Egg Bhurji", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Prawn Balchao", category: "Dal & Curry", region: "West Indian" },
  { name: "Clam Masala", category: "Dal & Curry", region: "South Indian" },
  { name: "Crab Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Mutton Keema", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Aloo Shimla Mirch", category: "Dal & Curry", region: "North Indian" },
  { name: "Kaju Curry", category: "Dal & Curry", region: "North Indian" },
  { name: "Corn Palak", category: "Dal & Curry", region: "North Indian" },
  { name: "Karela Sabzi", category: "Dal & Curry", region: "North Indian" },
  { name: "Batata Bhaji", category: "Dal & Curry", region: "West Indian" },
  { name: "Matki Usal", category: "Dal & Curry", region: "West Indian" },
  { name: "Misal Pav", category: "Dal & Curry", region: "West Indian" },
  { name: "Pav Bhaji Masala", category: "Dal & Curry", region: "West Indian" },
  { name: "Egg Masala Curry", category: "Dal & Curry", region: "Pan-Indian" },
  { name: "Vegetable Kolhapuri", category: "Dal & Curry", region: "West Indian" },
  { name: "Chicken Xacuti", category: "Dal & Curry", region: "West Indian" },
  { name: "Malabar Chicken Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Thalassery Mutton Curry", category: "Dal & Curry", region: "South Indian" },
  { name: "Pesarattu Curry", category: "Dal & Curry", region: "South Indian" },

  // ── Rice & Biryani (80) ──────────────────────────────────────
  { name: "Chicken Biryani", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Mutton Biryani", category: "Rice & Biryani", region: "North Indian" },
  { name: "Vegetable Biryani", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Hyderabadi Dum Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Lucknowi Biryani", category: "Rice & Biryani", region: "North Indian" },
  { name: "Kolkata Biryani", category: "Rice & Biryani", region: "East Indian" },
  { name: "Egg Biryani", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Prawn Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Paneer Biryani", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Jeera Rice", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Lemon Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Curd Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Tomato Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Coconut Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Puliyodharai", category: "Rice & Biryani", region: "South Indian" },
  { name: "Vangi Bath", category: "Rice & Biryani", region: "South Indian" },
  { name: "Sambar Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Pongal", category: "Rice & Biryani", region: "South Indian" },
  { name: "Venn Pongal", category: "Rice & Biryani", region: "South Indian" },
  { name: "Khichdi", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Moong Dal Khichdi", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Masala Khichdi", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Pulao", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Vegetable Pulao", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Matar Pulao", category: "Rice & Biryani", region: "North Indian" },
  { name: "Mushroom Pulao", category: "Rice & Biryani", region: "North Indian" },
  { name: "Chicken Fried Rice", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Egg Fried Rice", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Schezwan Fried Rice", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Rajma Chawal", category: "Rice & Biryani", region: "North Indian" },
  { name: "Dal Chawal", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Chole Chawal", category: "Rice & Biryani", region: "North Indian" },
  { name: "Bisi Bele Bath", category: "Rice & Biryani", region: "South Indian" },
  { name: "Ambur Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Dindigul Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Chettinad Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Malabar Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Thalassery Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Kappa Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Tamarind Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Capsicum Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Peas Pulao", category: "Rice & Biryani", region: "North Indian" },
  { name: "Saffron Rice", category: "Rice & Biryani", region: "North Indian" },
  { name: "Aloo Biryani", category: "Rice & Biryani", region: "North Indian" },
  { name: "Methi Pulao", category: "Rice & Biryani", region: "North Indian" },
  { name: "Corn Pulao", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Spinach Rice", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Bhuna Khichdi", category: "Rice & Biryani", region: "North Indian" },
  { name: "Vaghareli Khichdi", category: "Rice & Biryani", region: "West Indian" },
  { name: "Tawa Pulao", category: "Rice & Biryani", region: "West Indian" },
  { name: "Hariyali Pulao", category: "Rice & Biryani", region: "North Indian" },
  { name: "Kofta Biryani", category: "Rice & Biryani", region: "North Indian" },
  { name: "Soya Biryani", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Jackfruit Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Fish Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Nalli Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Kaima Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Ghee Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Neychoru", category: "Rice & Biryani", region: "South Indian" },
  { name: "Kichadi Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Beaten Rice Upma", category: "Rice & Biryani", region: "South Indian" },
  { name: "Mint Rice", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Kashmiri Pulao", category: "Rice & Biryani", region: "North Indian" },
  { name: "Zarda Rice", category: "Rice & Biryani", region: "North Indian" },
  { name: "Chicken Tikka Biryani", category: "Rice & Biryani", region: "North Indian" },
  { name: "Achari Biryani", category: "Rice & Biryani", region: "North Indian" },
  { name: "Malabar Mushroom Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Brown Rice Khichdi", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Sesame Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Groundnut Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Curry Leaf Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Oats Pongal", category: "Rice & Biryani", region: "South Indian" },
  { name: "Broken Wheat Khichdi", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Quinoa Khichdi", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Raw Banana Rice", category: "Rice & Biryani", region: "South Indian" },
  { name: "Hyderabadi Veg Biryani", category: "Rice & Biryani", region: "South Indian" },
  { name: "Mushroom Biryani", category: "Rice & Biryani", region: "Pan-Indian" },
  { name: "Baby Corn Pulao", category: "Rice & Biryani", region: "Pan-Indian" },

  // ── Breakfast & Snacks (80) ──────────────────────────────────
  { name: "Masala Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Plain Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Rava Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Set Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Neer Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Uttapam", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Idli", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Medu Vada", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Upma", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Rava Upma", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Poha", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Kanda Poha", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Aloo Paratha", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Gobi Paratha", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Paneer Paratha", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Mooli Paratha", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Methi Paratha", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Puri", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Bhatura", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Chole Bhature", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Besan Chilla", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Moong Dal Chilla", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Pesarattu", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Oats Idli", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Rava Idli", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Bread Upma", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Vegetable Oats Upma", category: "Breakfast & Snacks", region: "Pan-Indian" },
  { name: "Poha Cutlets", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Sabudana Khichdi", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Sabudana Vada", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Batata Vada", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Vada Pav", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Pav Bhaji", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Dhokla", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Handvo", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Khandvi", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Thepla", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Muthia", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Aamras Puri", category: "Breakfast & Snacks", region: "West Indian" },
  { name: "Aloo Tikki", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Samosa", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Pakora", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Onion Pakoda", category: "Breakfast & Snacks", region: "Pan-Indian" },
  { name: "Bread Pakoda", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Aloo Bonda", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Punugulu", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Mysore Bonda", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Akki Roti", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Ragi Mudde", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Puttu", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Appam", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Idiyappam", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Pidi", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Ela Ada", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Egg Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Cheese Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Spring Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Kozhukattai", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Pidi Kozhukattai", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Adai", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Litti Chokha", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Sattu Paratha", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Malpua", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Pitha", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Luchi", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Kochuri", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Radhaballabhi", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Aloo Chop", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Mughlai Paratha", category: "Breakfast & Snacks", region: "East Indian" },
  { name: "Puri Aloo", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Masala Maggi", category: "Breakfast & Snacks", region: "Pan-Indian" },
  { name: "Bread Omelette", category: "Breakfast & Snacks", region: "Pan-Indian" },
  { name: "Paniyaram", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Ragi Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Wheat Dosa", category: "Breakfast & Snacks", region: "South Indian" },
  { name: "Quinoa Upma", category: "Breakfast & Snacks", region: "Pan-Indian" },
  { name: "Sooji Halwa Puri", category: "Breakfast & Snacks", region: "North Indian" },
  { name: "Masala Puri", category: "Breakfast & Snacks", region: "South Indian" },

  // ── Bread & Roti (50) ────────────────────────────────────────
  { name: "Roti", category: "Bread & Roti", region: "Pan-Indian" },
  { name: "Chapati", category: "Bread & Roti", region: "Pan-Indian" },
  { name: "Phulka", category: "Bread & Roti", region: "Pan-Indian" },
  { name: "Tandoori Roti", category: "Bread & Roti", region: "North Indian" },
  { name: "Naan", category: "Bread & Roti", region: "North Indian" },
  { name: "Garlic Naan", category: "Bread & Roti", region: "North Indian" },
  { name: "Butter Naan", category: "Bread & Roti", region: "North Indian" },
  { name: "Laccha Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Rumali Roti", category: "Bread & Roti", region: "North Indian" },
  { name: "Kulcha", category: "Bread & Roti", region: "North Indian" },
  { name: "Amritsari Kulcha", category: "Bread & Roti", region: "North Indian" },
  { name: "Missi Roti", category: "Bread & Roti", region: "North Indian" },
  { name: "Bajra Roti", category: "Bread & Roti", region: "West Indian" },
  { name: "Jowar Roti", category: "Bread & Roti", region: "West Indian" },
  { name: "Makki Ki Roti", category: "Bread & Roti", region: "North Indian" },
  { name: "Besan Roti", category: "Bread & Roti", region: "North Indian" },
  { name: "Methi Thepla", category: "Bread & Roti", region: "West Indian" },
  { name: "Puran Poli", category: "Bread & Roti", region: "West Indian" },
  { name: "Pathiri", category: "Bread & Roti", region: "South Indian" },
  { name: "Malabar Parotta", category: "Bread & Roti", region: "South Indian" },
  { name: "Kerala Porotta", category: "Bread & Roti", region: "South Indian" },
  { name: "Veechu Parotta", category: "Bread & Roti", region: "South Indian" },
  { name: "Kothu Parotta", category: "Bread & Roti", region: "South Indian" },
  { name: "Akki Rotti", category: "Bread & Roti", region: "South Indian" },
  { name: "Jolada Rotti", category: "Bread & Roti", region: "South Indian" },
  { name: "Ragi Rotti", category: "Bread & Roti", region: "South Indian" },
  { name: "Puri Bhaji", category: "Bread & Roti", region: "West Indian" },
  { name: "Sheermal", category: "Bread & Roti", region: "North Indian" },
  { name: "Bakarkhani", category: "Bread & Roti", region: "North Indian" },
  { name: "Tandoori Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Stuffed Kulcha", category: "Bread & Roti", region: "North Indian" },
  { name: "Dal Puri", category: "Bread & Roti", region: "East Indian" },
  { name: "Bedmi Puri", category: "Bread & Roti", region: "North Indian" },
  { name: "Khasta Kachori", category: "Bread & Roti", region: "North Indian" },
  { name: "Mawa Kachori", category: "Bread & Roti", region: "West Indian" },
  { name: "Onion Kachori", category: "Bread & Roti", region: "West Indian" },
  { name: "Pyaaz Ki Kachori", category: "Bread & Roti", region: "North Indian" },
  { name: "Baked Naan", category: "Bread & Roti", region: "North Indian" },
  { name: "Cheese Kulcha", category: "Bread & Roti", region: "North Indian" },
  { name: "Aloo Kulcha", category: "Bread & Roti", region: "North Indian" },
  { name: "Whole Wheat Naan", category: "Bread & Roti", region: "North Indian" },
  { name: "Stuffed Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Mixed Flour Roti", category: "Bread & Roti", region: "Pan-Indian" },
  { name: "Ragi Roti", category: "Bread & Roti", region: "South Indian" },
  { name: "Oats Roti", category: "Bread & Roti", region: "Pan-Indian" },
  { name: "Spinach Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Beet Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Carrot Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Corn Paratha", category: "Bread & Roti", region: "North Indian" },
  { name: "Keema Paratha", category: "Bread & Roti", region: "North Indian" },

  // ── Sweets & Desserts (60) ───────────────────────────────────
  { name: "Gulab Jamun", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Jalebi", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Rasgulla", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Rasmalai", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Kheer", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Phirni", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Halwa", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Sooji Halwa", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Gajar Ka Halwa", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Besan Ladoo", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Motichur Ladoo", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Rava Ladoo", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Coconut Ladoo", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Til Ladoo", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Peanut Ladoo", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Barfi", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Kaju Katli", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Peda", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Shrikhand", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Basundi", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Rabdi", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Kulfi", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Falooda", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Sewai Kheer", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Mango Kheer", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Payasam", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Semiya Payasam", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Pal Payasam", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Pradhaman", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Ada Pradhaman", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Mysore Pak", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Puttu Kadala", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Unniyappam", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Ariselu", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Pootharekulu", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Mango Halwa", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Rava Kesari", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Chakli Ladoo", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Modak", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Puran Poli Sweet", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Sandesh", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Mishti Doi", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Chhena Poda", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Chena Gaja", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Gaja Cake", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Shahi Tukda", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Double Ka Meetha", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Moong Dal Halwa", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Pinni", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Balushahi", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Ghevar", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Mawa Bati", category: "Sweets & Desserts", region: "West Indian" },
  { name: "Coconut Burfi", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Chocolate Barfi", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Banana Halwa", category: "Sweets & Desserts", region: "South Indian" },
  { name: "Bread Halwa", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Apple Kheer", category: "Sweets & Desserts", region: "Pan-Indian" },
  { name: "Makhane Ki Kheer", category: "Sweets & Desserts", region: "North Indian" },
  { name: "Chum Chum", category: "Sweets & Desserts", region: "East Indian" },
  { name: "Khaja", category: "Sweets & Desserts", region: "East Indian" },

  // ── Street Food (60) ─────────────────────────────────────────
  { name: "Pani Puri", category: "Street Food", region: "Pan-Indian" },
  { name: "Bhel Puri", category: "Street Food", region: "West Indian" },
  { name: "Sev Puri", category: "Street Food", region: "West Indian" },
  { name: "Ragda Pattice", category: "Street Food", region: "West Indian" },
  { name: "Dabeli", category: "Street Food", region: "West Indian" },
  { name: "Sev Tameta", category: "Street Food", region: "West Indian" },
  { name: "Dahi Puri", category: "Street Food", region: "West Indian" },
  { name: "Dahi Vada", category: "Street Food", region: "Pan-Indian" },
  { name: "Papdi Chaat", category: "Street Food", region: "North Indian" },
  { name: "Aloo Chaat", category: "Street Food", region: "North Indian" },
  { name: "Fruit Chaat", category: "Street Food", region: "North Indian" },
  { name: "Ram Ladoo", category: "Street Food", region: "North Indian" },
  { name: "Golgappa", category: "Street Food", region: "North Indian" },
  { name: "Daulat Ki Chaat", category: "Street Food", region: "North Indian" },
  { name: "Matar Kulcha", category: "Street Food", region: "North Indian" },
  { name: "Chhole Tikki", category: "Street Food", region: "North Indian" },
  { name: "Bread Roll", category: "Street Food", region: "North Indian" },
  { name: "Kathi Roll", category: "Street Food", region: "East Indian" },
  { name: "Egg Kathi Roll", category: "Street Food", region: "East Indian" },
  { name: "Jhal Muri", category: "Street Food", region: "East Indian" },
  { name: "Telebhaja", category: "Street Food", region: "East Indian" },
  { name: "Ghugni Chaat", category: "Street Food", region: "East Indian" },
  { name: "Puchka", category: "Street Food", region: "East Indian" },
  { name: "Churmur", category: "Street Food", region: "East Indian" },
  { name: "Chicken Roll", category: "Street Food", region: "East Indian" },
  { name: "Bajji", category: "Street Food", region: "South Indian" },
  { name: "Mirchi Bajji", category: "Street Food", region: "South Indian" },
  { name: "Banana Bajji", category: "Street Food", region: "South Indian" },
  { name: "Sundal", category: "Street Food", region: "South Indian" },
  { name: "Kuzhi Paniyaram", category: "Street Food", region: "South Indian" },
  { name: "Masala Vada", category: "Street Food", region: "South Indian" },
  { name: "Egg Puff", category: "Street Food", region: "South Indian" },
  { name: "Chicken Puff", category: "Street Food", region: "South Indian" },
  { name: "Samosa Chaat", category: "Street Food", region: "North Indian" },
  { name: "Raj Kachori", category: "Street Food", region: "North Indian" },
  { name: "Tokri Chaat", category: "Street Food", region: "North Indian" },
  { name: "Corn Chaat", category: "Street Food", region: "Pan-Indian" },
  { name: "Masala Muri", category: "Street Food", region: "East Indian" },
  { name: "Kachori Chaat", category: "Street Food", region: "North Indian" },
  { name: "Momos", category: "Street Food", region: "North Indian" },
  { name: "Fried Momos", category: "Street Food", region: "North Indian" },
  { name: "Chicken Momos", category: "Street Food", region: "North Indian" },
  { name: "Veg Momos", category: "Street Food", region: "North Indian" },
  { name: "Frankies", category: "Street Food", region: "West Indian" },
  { name: "Keema Pav", category: "Street Food", region: "West Indian" },
  { name: "Bombay Sandwich", category: "Street Food", region: "West Indian" },
  { name: "Masala Toast", category: "Street Food", region: "West Indian" },
  { name: "Cheese Toast", category: "Street Food", region: "Pan-Indian" },
  { name: "Sada Dosa", category: "Street Food", region: "South Indian" },
  { name: "Spring Roll", category: "Street Food", region: "Pan-Indian" },
  { name: "Aloo Pakora", category: "Street Food", region: "Pan-Indian" },
  { name: "Gobi Pakora", category: "Street Food", region: "Pan-Indian" },
  { name: "Paneer Pakora", category: "Street Food", region: "North Indian" },
  { name: "Fish Pakora", category: "Street Food", region: "Pan-Indian" },
  { name: "Chicken Pakora", category: "Street Food", region: "Pan-Indian" },
  { name: "Prawn Pakora", category: "Street Food", region: "Pan-Indian" },
  { name: "Aloo Tikki Chaat", category: "Street Food", region: "North Indian" },
  { name: "Shakarkandi Chaat", category: "Street Food", region: "North Indian" },
  { name: "Mathri", category: "Street Food", region: "North Indian" },
  { name: "Namak Para", category: "Street Food", region: "North Indian" },

  // ── Soups & Lentils (40) ─────────────────────────────────────
  { name: "Tomato Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Sweet Corn Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Manchow Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Lemon Coriander Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Mulligatawny Soup", category: "Soups & Lentils", region: "South Indian" },
  { name: "Rasam Soup", category: "Soups & Lentils", region: "South Indian" },
  { name: "Pepper Rasam", category: "Soups & Lentils", region: "South Indian" },
  { name: "Garlic Rasam", category: "Soups & Lentils", region: "South Indian" },
  { name: "Tomato Rasam", category: "Soups & Lentils", region: "South Indian" },
  { name: "Jeera Rasam", category: "Soups & Lentils", region: "South Indian" },
  { name: "Shorba", category: "Soups & Lentils", region: "North Indian" },
  { name: "Chicken Shorba", category: "Soups & Lentils", region: "North Indian" },
  { name: "Yakhni Soup", category: "Soups & Lentils", region: "North Indian" },
  { name: "Nalli Shorba", category: "Soups & Lentils", region: "North Indian" },
  { name: "Palak Shorba", category: "Soups & Lentils", region: "North Indian" },
  { name: "Corn Spinach Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Vegetable Clear Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Hot and Sour Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Coconut Milk Soup", category: "Soups & Lentils", region: "South Indian" },
  { name: "Raw Mango Rasam", category: "Soups & Lentils", region: "South Indian" },
  { name: "Tamarind Rasam", category: "Soups & Lentils", region: "South Indian" },
  { name: "Moong Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Masoor Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Dal Shorba", category: "Soups & Lentils", region: "North Indian" },
  { name: "Rajma Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Broccoli Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Pumpkin Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Carrot Ginger Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Spinach Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Mushroom Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Cauliflower Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Drumstick Soup", category: "Soups & Lentils", region: "South Indian" },
  { name: "Chicken Noodle Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Egg Drop Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Wonton Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Coriander Mint Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Oats Soup", category: "Soups & Lentils", region: "Pan-Indian" },
  { name: "Kokum Kadhi", category: "Soups & Lentils", region: "West Indian" },
  { name: "Sol Kadi", category: "Soups & Lentils", region: "West Indian" },
  { name: "Lasun Chutney Soup", category: "Soups & Lentils", region: "West Indian" },

  // ── Drinks & Beverages (30) ──────────────────────────────────
  { name: "Mango Lassi", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Sweet Lassi", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Masala Chai", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Ginger Tea", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Kashmiri Kahwa", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Thandai", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Rose Sharbat", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Jaljeera", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Aam Panna", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Nimbu Pani", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Chaas", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Masala Chaas", category: "Drinks & Beverages", region: "West Indian" },
  { name: "Coconut Water Drink", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Filter Coffee", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Sulaimani Tea", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Sambaram", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Panakam", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Nannari Sherbet", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Bel Sharbat", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Sattu Drink", category: "Drinks & Beverages", region: "East Indian" },
  { name: "Thandai Milk", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Haldi Doodh", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Masala Milk", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Badam Milk", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Kesar Milk", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Watermelon Juice", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Sugarcane Juice", category: "Drinks & Beverages", region: "Pan-Indian" },
  { name: "Tamarind Juice", category: "Drinks & Beverages", region: "South Indian" },
  { name: "Kokum Sharbat", category: "Drinks & Beverages", region: "West Indian" },
  { name: "Paan Sharbat", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Gond Katira Sharbat", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Chandan Sharbat", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Khus Sharbat", category: "Drinks & Beverages", region: "North Indian" },
  { name: "Imli Ka Amlana", category: "Drinks & Beverages", region: "North Indian" },
];
